language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test timeline-blog --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng test ngx-time-line --watch=false --progress=false --browsers=ChromeHeadlessCI  
  - ng build --prod
  - ng build ngx-time-line

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/timeline-blog
  on:
    branch: master

deploy:
  provider: npm
  email: "laxin204@gmail.com"
  api_key: $NPM_TOKEN
  local_dir: dist/ngx-time-line
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change